[[config]]
Configuration
-------------

Key Configuration
~~~~~~~~~~~~~~~~~

The key configuration files are necessary to join the network.  They
authenticate peers and the message traffic that flows between peers.  It does
not authenticate the local bridging protocols RV, NATS, or Redis.

Generating a master config is done with the `ms_gen_key` program.  The default
location for the config directory is `./config`, other locations are specified
with the `-d` option.

Initially, the config directory is empty.  Initialize with some users and a
service name.

----
  $ ms_gen_key -u A B C -s test
  create dir  config                          -- the configure directory
  create file config/.salt                    -- generate new salt
  create file config/.pass                    -- generated a new password
  create file config/config.yaml              -- base include file
  create file config/param.yaml               -- parameters file
  create file config/svc_test.yaml            -- defines the service and signs users
  create file config/user_A_svc_test.yaml     -- defines the user
  create file config/user_B_svc_test.yaml     -- defines the user
  create file config/user_C_svc_test.yaml     -- defines the user
  OK? y
  done
----

Exporting the keys for each of the nodes causes the `.pass` file the change and
the unnecessary private keys to be removed.  The only private key that remains,
is for the peer.  This trimmed configuration allows the peer to run, but not
generate new peers because the private key of the service is not present.

----
  $ ms_gen_key -x A B C -s test
  - Loading service "test"               
  - Signatures ok                        
  create dir  A                          -- exported configure directory
  create file A/.salt                    -- a copy of salt
  create file A/.pass                    -- generated a new password
  create file A/param.yaml               -- a copy of param
  create file A/config.yaml              -- base include file
  create file A/svc_test.yaml            -- defines the service and signs users
  create file A/user_A_svc_test.yaml     -- defines the user
  create file A/user_B_svc_test.yaml     -- defines the user
  create file A/user_C_svc_test.yaml     -- defines the user
  create dir  B                          -- exported configure directory
  create file B/.salt                    -- a copy of salt
  create file B/.pass                    -- generated a new password
  create file B/param.yaml               -- a copy of param
  create file B/config.yaml              -- base include file
  create file B/svc_test.yaml            -- defines the service and signs users
  create file B/user_A_svc_test.yaml     -- defines the user
  create file B/user_B_svc_test.yaml     -- defines the user
  create file B/user_C_svc_test.yaml     -- defines the user
  create dir  C                          -- exported configure directory
  create file C/.salt                    -- a copy of salt
  create file C/.pass                    -- generated a new password
  create file C/param.yaml               -- a copy of param
  create file C/config.yaml              -- base include file
  create file C/svc_test.yaml            -- defines the service and signs users
  create file C/user_A_svc_test.yaml     -- defines the user
  create file C/user_B_svc_test.yaml     -- defines the user
  create file C/user_C_svc_test.yaml     -- defines the user
  OK? y
  done
----

Copy the A config to the A node/config, the B config directory to the B
node/config, etc.  The `.pass` file is unique for each peer so that it can be
removed after running the server, rendering the configured keys unreadable
until the `.pass` file is restored or the peer's config is regenerated from the
master config.

The copy of the master config includes a copy of the `param.yaml`, as that can
contain global configuration, but doesn't copy any local configuration such as
startup and network configuration.

The master config will also work, so just copying it to the peers will allow
them to run if this type of security is unnecessary.

Parameters
~~~~~~~~~~

The parameters section of the configuration is used to lookup values that can
alter the behavior of the server.  These fields can be set anywhere in the
config files, but are usually in the "param.yaml" or "startup.yaml" files.
Since the "config.yaml" includes "*.yaml", any yaml file in the config
directory can contain parameters.  Any field value pair which is not in a
service, user, service, transport, or group section is added to the parameters
section.

This configuration is a list of parameters:

----
parameters:
  pass: .pass
  salt: .salt
heartbeat: 5 secs
reliability: 10 secs
tcp_noencrypt: true
listen:
  - mymesh
  - myweb
connect:
  - mytcp
----

The "parameters:" structure is optional and not necessary to define them.

[%autowidth,options="header",grid="cols",stripes="even"]
|=============================================
| Name            | Type     | Default | Description
| salt            | filename | none    | File to find encryption salt
| pass            | filename | none    | File to find encryption password
| salt_data       | string   | none    | Base 64 encoded encryption salt
| pass_data       | string   | none    | Base 64 encoded encryption password
| listen          | array    | none    | Startup listen transports
| connect         | array    | none    | Startup connect transports
| pub_window_size | bytes    | 4 MB    | Size of publish window
| sub_window_size | bytes    | 4 MB    | Size of subscribe window
| pub_window_time | time     | 10 secs | Time of publish window
| sub_window_time | time     | 10 secs | Time of subscribe window
| heartbeat       | time     | 10 secs | Interval of heartbeat
| reliability     | time     | 15 secs | Time of publish reliability
| timestamp       | string   | LOCAL   | Log using local time or GMT
| pid_file        | string   | none    | Daemon pid file
| map_file        | string   | none    | Use for key value storage
| db_num          | string   | none    | Default db number for key value
| ipc_name        | string   | none    | Connect to IPC sockets
| tcp_timeout     | time     | 10 secs | Default timeout for TCP/mesh connect
| tcp_ipv4only    | boolean  | false   | Use IPv4 addressing only
| tcp_ipv6only    | boolean  | false   | Use IPv6 addressing only
| tcp_noencrypt   | boolean  | false   | Default for TCP/mesh encryption
|=============================================

- salt, pass, salt_data, pass_data -- The salt, pass or salt_data, pass_data
  are required for startup.  The keys defined in the configuration are
  encrypted with these values.  Any key derived during execution is mixed with
  the salt and must be the same in all peers.

- listen, connect -- The startup transports.  They are started before any other
  events are processed.  If a listen fails, then the program exits.  A connect
  failure will not cause an exit, since it retries.

- pub_window_size, sub_window_size, pub_window_time, sub_window_time -- These
  track the sequence numbers of messages sent and received.  They are described
  in <<pub_window>>.

- heartbeat -- The interval which heartbeats are published to directly
  connected peers.  A link is not active when a heartbeat is missed for
  1.5 times this interval.  The link is reactivated when a heartbeat is
  received.

- timestamp -- When set to GMT, the time stamps are not offset by the local
  timezone.

- pid_file -- A file that contains the process id when forked in rvd mode.

- map_file -- If a Redis transport is used, this is where the data is stored.
  If no map is defined, then the data stored will fail and data retrieved will
  be zero.  The `kv_server` command will initialize a map file.

- db_num -- The default database number for the Redis transport.

- ipc_name -- When set, allows IPC processes to connect through Unix sockets
  and subscription maps using the same name.  If the processes are shutdown,
  they will restart or stop the subscriptions using the maps.

- tcp_timeout -- The default retry timeout for TCP and mesh connections.

- tcp_ip4only -- Resolve DNS hostnames to IPv4 addresses only.

- tcp_ip6only -- Resolve DNS hostnames to IPv6 addresses only.

- tcp_noencrypt -- When true, the default for TCP and mesh connections is to
  to not encrypt the traffic.
