[[config]]
Configuration
-------------

Key Configuration
~~~~~~~~~~~~~~~~~

The key configuration files are necessary to join the network.  They
authenticate peers and the message traffic that flows between peers.  It does
not authenticate the local bridging protocols RV, NATS, or Redis.

Generating a master config is done with the `ms_gen_key` program.  The default
location for the config directory is `./config`, other locations are specified
with the `-d` option.

Initially, the config directory is empty.  Initialize with some users and a
service name.

----
$ ms_gen_key -u A B C -s test
create dir  config                          -- the configure directory
create file config/.salt                    -- generate new salt
create file config/.pass                    -- generated a new password
create file config/config.yaml              -- base include file
create file config/param.yaml               -- parameters file
create file config/svc_test.yaml            -- defines the service and signs users
create file config/user_A_svc_test.yaml     -- defines the user
create file config/user_B_svc_test.yaml     -- defines the user
create file config/user_C_svc_test.yaml     -- defines the user
OK? y
done
----

Exporting the keys for each of the nodes causes the `.pass` file the change and
the unnecessary private keys to be removed.  The only private key that remains,
is for the peer.  This trimmed configuration allows the peer to run, but not
generate new peers because the private key of the service is not present.

----
$ ms_gen_key -x A B C -s test
- Loading service "test"               
- Signatures ok                        
create dir  A                          -- exported configure directory
create file A/.salt                    -- a copy of salt
create file A/.pass                    -- generated a new password
create file A/param.yaml               -- a copy of param
create file A/config.yaml              -- base include file
create file A/svc_test.yaml            -- defines the service and signs users
create file A/user_A_svc_test.yaml     -- defines the user
create file A/user_B_svc_test.yaml     -- defines the user
create file A/user_C_svc_test.yaml     -- defines the user
create dir  B                          -- exported configure directory
create file B/.salt                    -- a copy of salt
create file B/.pass                    -- generated a new password
create file B/param.yaml               -- a copy of param
create file B/config.yaml              -- base include file
create file B/svc_test.yaml            -- defines the service and signs users
create file B/user_A_svc_test.yaml     -- defines the user
create file B/user_B_svc_test.yaml     -- defines the user
create file B/user_C_svc_test.yaml     -- defines the user
create dir  C                          -- exported configure directory
create file C/.salt                    -- a copy of salt
create file C/.pass                    -- generated a new password
create file C/param.yaml               -- a copy of param
create file C/config.yaml              -- base include file
create file C/svc_test.yaml            -- defines the service and signs users
create file C/user_A_svc_test.yaml     -- defines the user
create file C/user_B_svc_test.yaml     -- defines the user
create file C/user_C_svc_test.yaml     -- defines the user
OK? y
done
----

Copy the A config to the A node/config, the B config directory to the B
node/config, etc.  The `.pass` file is unique for each peer so that it can be
removed after running the server, rendering the configured keys unreadable
until the `.pass` file is restored or the peer's config is regenerated from the
master config.

The copy of the master config includes a copy of the `param.yaml`, as that can
contain global configuration, but doesn't copy any local configuration such as
startup and network configuration.

The master config will also work, so just copying it to the peers will allow
them to run if this type of security is unnecessary.

Single File Configuration
~~~~~~~~~~~~~~~~~~~~~~~~~

The `ms_gen_key` option `-o` will concatenate the configuration into a single
file:

----
$ ms_gen_key -s test -o test.yaml
create dir  config                   -- the configure directory
create file config/.salt             -- generate new salt
create file config/.pass             -- generated a new password
create file config/config.yaml       -- base include file
create file config/param.yaml        -- parameters file
create file config/svc_test.yaml     -- defines the service and signs users
OK? y
done
- Output config to "test.yaml"
----

Running `ms_server -d config` configuration from a directory and running
`ms_server -d test.yaml` will load the configuration from a file.  In both
cases, the configuration loaded will be the same.

A test network can be set up using only the loopback interface by describing
the network using a format output by the link:#show_graph[show_graph] command.
The format of this is:

----
node A B C D
tcp_link_ab A B : 200
tcp_link_bc B C : 100
tcp_link_ac A C : 200
tcp_link_bd B D : 200
tcp_link_dc D C : 300
----

The `node` line declares all of the users.  The `tcp_` lines describe how the
users are connected.  The number following the ':' is the cost of the
transport.

Running the `ms_test_adj` program with this description will generate a
configuration, saved in a file called "graph.txt" and output to "graph.yaml":

----
$ ms_test_adj -l graph.txt > graph.yaml
----

The `-l` option causes the links to be resolved by exchanging messages over the
loopback interface.  At the bottom of the "graph.yaml" created, there will be
commands in comments to run this configuration.   Running these will create 4
users in a network describe by the graph.  The following uses those commands
with the first three running in the background and the last with a console
attached to it, but you could run each in a different terminal with consoles
attached in order to test with the link:#test_sub[sub] and
link:#test_trace[trace] commands to test how messages would be routed through
the network.

[source%nowrap]
----
$ ms_server -d graph.yaml -u A -t link_ab.listen link_ac.listen &
$ ms_server -d graph.yaml -u B -t link_ab.connect link_bc.listen link_bd.listen &
$ ms_server -d graph.yaml -u C -t link_ac.connect link_bc.connect link_dc.listen &
$ ms_server -d graph.yaml -u D -t link_bd.connect link_dc.connect -c
----

In addition to "tcp" type links, you could also define "mesh" and "pgm" types,
but the pgm would require non-loopback interface that has multicast, like a
Linux bridge.

----
node A B C D
mesh_link_abcd A B C D : 100 1000 100 1000
mesh_link_abcd2 A B C D : 1000 100 1000 100
----

The above graph would create two meshes, with different costs for some of the
paths.  This would route messages over both meshes by sharding the subject
space and using one mesh for half of the subject space and the other mesh for
the other half.

There is a graphical interface to view the network using the
https://js.cytoscape.org/[cytoscape] package.

[source%nowrap]
----
$ ms_server -c
chex.test[0vEvE73U78HkGZUgBK94mQ]@chex[10]> configure transport web type web port 8080 listen 127.0.0.1
Transport (web) updated
chex.test[0vEvE73U78HkGZUgBK94mQ]@chex[11]> listen web
Transport (web) started listening
0209 22:54:25.382  web: web start listening on 127.0.0.1:8080
0209 22:54:25.382  http_url http://127.0.0.1:8080
----

Connect to the url http://127.0.0.1:8080/graph_nodes.html with a web browser
and paste the graph text into the text box after erasing the existing text,
then click "show graph".

[[parameters]]
Parameters
~~~~~~~~~~

The parameters section of the configuration is used to lookup values that can
alter the behavior of the server.  These fields can be set anywhere in the
config files, but are usually in the "param.yaml" or "startup.yaml" files.
Since the "config.yaml" includes "*.yaml", any yaml file in the config
directory can contain parameters.  Any field value pair which is not in a
service, user, service, transport, or group section is added to the parameters
section.

This configuration is a list of parameters:

----
parameters:
  pass: .pass
  salt: .salt
heartbeat: 5 secs
reliability: 10 secs
tcp_noencrypt: true
listen:
  - mymesh
  - myweb
connect:
  - mytcp
----

The "parameters:" structure is optional and not necessary to define them.

[%autowidth,options="header",grid="cols",stripes="even"]
|=============================================
| Name                | Type     | Default | Description
| salt                | filename | none    | File to find encryption salt
| pass                | filename | none    | File to find encryption password
| salt_data           | string   | none    | Base 64 encoded encryption salt
| pass_data           | string   | none    | Base 64 encoded encryption password
| listen              | array    | none    | Startup listen transports
| connect             | array    | none    | Startup connect transports
| pub_window_size     | bytes    | 4 MB    | Size of publish window
| sub_window_size     | bytes    | 8 MB    | Size of subscribe window
| pub_window_time     | time     | 10 secs | Time of publish window
| sub_window_time     | time     | 10 secs | Time of subscribe window
| heartbeat           | time     | 10 secs | Interval of heartbeat
| reliability         | time     | 15 secs | Time of publish reliability
| timestamp           | string   | LOCAL   | Log using local time or GMT
| pid_file            | string   | none    | Daemon pid file
| map_file            | string   | none    | Use for key value storage
| db_num              | string   | none    | Default db number for key value
| ipc_name            | string   | none    | Connect to IPC sockets
| tcp_timeout         | time     | 10 secs | Default timeout for TCP/mesh connect
| tcp_ipv4only        | boolean  | false   | Use IPv4 addressing only
| tcp_ipv6only        | boolean  | false   | Use IPv6 addressing only
| tcp_noencrypt       | boolean  | false   | Default for TCP/mesh encryption
| tcp_write_timeout   | time     | 10 secs | Timeout for TCP write
| tcp_write_highwater | bytes    | 1 MB    | TCP write buffer size
| idle_busy           | count    | 16      | Busy wait loop count
|=============================================

- salt, pass, salt_data, pass_data -- The salt, pass or salt_data, pass_data
  are required for startup.  The keys defined in the configuration are
  encrypted with these values.  Any key derived during execution is mixed with
  the salt and must be the same in all peers.

- listen, connect -- The startup transports.  They are started before any other
  events are processed.  If a listen fails, then the program exits.  A connect
  failure will not cause an exit, since it retries.

- pub_window_size, sub_window_size, pub_window_time, sub_window_time -- These
  track the sequence numbers of messages sent and received.  They are described
  in <<pub_window>>.

- heartbeat -- The interval which heartbeats are published to directly
  connected peers.  A link is not active when a heartbeat is missed for
  1.5 times this interval.  The link is reactivated when a heartbeat is
  received.

- timestamp -- When set to GMT, the time stamps are not offset by the local
  timezone.

- pid_file -- A file that contains the process id when forked in rvd mode.

- map_file -- If a Redis transport is used, this is where the data is stored.
  If no map is defined, then the data stored will fail and data retrieved will
  be zero.  The `kv_server` command will initialize a map file.

- db_num -- The default database number for the Redis transport.

- ipc_name -- When set, allows IPC processes to connect through Unix sockets
  and subscription maps using the same name.  If the processes are shutdown,
  they will restart or stop the subscriptions using the maps.

- tcp_timeout -- The default retry timeout for TCP and mesh connections.

- tcp_ip4only -- Resolve DNS hostnames to IPv4 addresses only.

- tcp_ip6only -- Resolve DNS hostnames to IPv6 addresses only.

- tcp_noencrypt -- When true, the default for TCP and mesh connections is to
  to not encrypt the traffic.

- tcp_write_timeout -- Amount of time to wait for TCP write progress if the
  write buffer is full.  After this time, socket is disconnected and messages
  lost.  When a TCP write buffer has equal or more than `tcp_write_highwater`
  bytes then backpressure can be applied to the sockets that are forwarding
  data, causing them to add latency waiting for the writer to have space
  available.

- tcp_write_highwater -- Amount of data to buffer for writing before applying
  back pressure to forwarding sockets.

- idle_busy -- Number of times to loop while no activity is present.  More
  looping while idle keeps the process on a CPU for lower latency at the
  expense of wasted CPU cycles.
