[[linkstate]]
Link State
----------

The Forwarding Set
~~~~~~~~~~~~~~~~~~

Each node in a network must construct a forwarding set for any message sent by
any peer.  A forwarding set instructs the node where to send a message so that
all subscribers of it will see the message exactly one time, when the network
is converged and stable.

A "converged network" is one where all peers agree that a link exists.  If
peer A has in it's database a link to peer B, then peer B must also have a
link to peer A.  If a link is missing, then the network tries to resolve the
difference by asking the peers with the discrepancy which is correct.

Every peer has a bloom filter that contains all of the subscriptions currently
active.  The links database tells each peer how the network can be traversed
for full coverage and the bloom filter prunes the coverage by dropping the
message when there are no subscriptions active that match the subject on the
other side of the link.

A simple redundant network is a circle:

----
dyna  --  ruby
            
  |        |
            
bond  --  chex
----

If the cost of each of the links is set to the default 1000, then the
forwarding set for dyna is the link to ruby and bond.  When ruby and bond
receive a message from dyna, only one of them will forward the message to chex.
The path cost from dyna -> ruby -> chex is equal to the path cost from dyna ->
bond -> chex.  The forwarding algorithm tracks the equal cost paths and ranks
them in order of peer age.  In the case that ruby is older than bond, then the
ranking of these routes would by 1. dyna -> ruby -> chex and 2. dyna -> bond ->
chex.  The top 4 ranked routes are saved as the forwarding sets, and selected
by the hash of the message subject.  In this case, half of the subjects
subscribed by chex and published from dyna would take the first path and the
other half would take the second path.

The method of ranking the paths by peer age is used because the stability
of the network is less affected when more transient peers are added and
subtracted from the link state database.

