Internal Protocol
-----------------

The protocol is asynchronous with timers to timeout RPCs and to throttle the
rate which peers back off retries.  As a result of this, the message flow for
a network configuration is variable and can change with different conditions.

The function of each message is encoded in the subjects with the arguments
passed as field values with some common flags and options encoded in the
message header.

Each message is authenticated a session key using a message HMAC.  The initial
key exchange is signed by either the service private key or a configured user
private key.  The heartbeat messages are also authenticated with a hello key
message HMAC derived from the service public key and the start time.  These are
messages that set up the initial key exchange before a session key is
established, but can be weakly authenticated since service public key is
encrypted at rest in the configuration and not shared over the network.

Any message that fails authentication is ignored.

Field Values
~~~~~~~~~~~~

Each field in a message is encoded with a type and length.  This allows new
fields to be added without disrupting the message parsing.  The first 16 bits
encodes the type, length and field id.  The rest of the field encodes the
value.  All integers are encoded in big endian.

----
fid = BRIDGE(3), type = OPAQUE_16(4) ( opaque 16 bytes )            144
|-+-+-+-+-+-+-+-|-+-+-+-+-+-+-+-|-+-+-+-+-+-+-+-|-+-+-+-+-+-+-+-|-+.. +
|1 1 x x 0 1 0 0 0 0 0 0 0 0 1 1|                                     |
 ^ ^     ^.....^ ^.............^ ^....................................
 | |         |        |                        |
 | primitive type(4)  fid(3)               128 bit bridge
 fixed
----

The types defined are bool (size:1), unsigned int (size:2,4,8), opaque
(size:16,32,64), string (max size:64k), long opaque (max size:4G).

The first two bits, fixed and primitive, indicate whether the type has a fixed
length, and whether the value is a field (primitive) or a message (not
primitive).  A message is another group of fields and is always encoded as a
long opaque with the primitive bit set to 0.  A message payload is always
encoded as a long opaque with the primitive bit set to 1.

The types are enumerated as:

[%autowidth,options="header",grid="cols",stripes="even"]
|=============================================
| Type           | Value      | Size
| bool           | 0          | 1 byte
| unsigned short | 1          | 2 bytes
| unsigned int   | 2          | 4 bytes
| unsigned long  | 3          | 8 bytes
| opaque 16      | 4          | 16 bytes
| opaque 32      | 5          | 32 bytes
| opaque 64      | 6          | 64 bytes
| string         | 7          | 16 bit length + up to 64K bytes
| long opaque    | 8          | 32 bit length + up to 4G bytes
|=============================================

The field values are aligned on 2 byte boundaries, so the value is padded one
byte when the value size is odd.  There are currently 76 different field ids
(fid) and a maximum of 256 (defined in the header file `msg.h`).

Message Framing
~~~~~~~~~~~~~~~

A message frame has 5 fixed length sections and 3 fields that are always
present and use two bytes.

These header fields are:

[%autowidth,options="header",grid="cols",stripes="even"]
|=============================
| Field          | Size       
| Version        | 1 bit      
| Message Type   | 2 bits     
| Message Option | 5 bits     
| Message Size   | 3 bytes    
| Subject Hash   | 4 bytes    
| Bridge         | 2 byte type + 16 bytes
| Message Digest | 2 byte type + 16 bytes
| Subject        | 2 byte type + 16 bit length + up to 64K
|=============================

The first 4 bytes encoded as:

----
bytes 0 -> 3 are ver(1), type(2), opt(5), message size (24)
 1               8               16              24              32
|-+-+-+-+-+-+-+-|-+-+-+-+-+-+-+-|-+-+-+-+-+-+-+-|-+-+-+-+-+-+-+-|
|1|0 0|0 0 0 0 0|0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0|
 ^ ^.^ ^.......^ ^.............................................^
 |    \    |                         |
ver(1)|   opt(0)                24 bit size(160)
     type(0)
----

The Message Type encodes 4 classes of messages:

[%autowidth,options="header",grid="cols",stripes="even"]
|==========================================
| Type         | Value | Description
| Mcast        | 0     | Multicast message with routeable payload
| Inbox        | 1     | Point to point message
| Router Alert | 2     | System link state or subscription update
| Heartbeat    | 3     | Neighbor link keep alive
|==========================================

A message that has routeable data always has the Multicast or Inbox type set.
The Inbox type message is also used for RPC style communication between peers.
The Router Alert type message alters the routing database by modifying the link
state or the subscription state.  A Heartbeat type is a periodic presence
update.  The peers which are directly connected are responsible for detecting
link failures.

The Option Flags is a bit mask that encodes options for messages with Multicast
and Inbox types that are routing data payloads to endpoints.
These are:

[%autowidth,options="header",grid="cols",stripes="even"]
|==========================================
| Option  | Value | Description
| Ack     | 1     | Endpoints ack the reception
| Trace   | 2     | All peers along the route ack the reception
| Any     | 4     | Message is an anycast, destination is one endpoint of many
| MC0     | 0     | Message is using multicast path 0
| MC1     | 8     | Message is using multicast path 1
| MC2     | 16    | Message is using multicast path 2
| MC3     | 24    | Message is using multicast path 3
|==========================================

The message size does not include the first 8 bytes, so the message frame size
is 8 + the message size field.  If the size is greater than 24 bits, then the
next 32 bits are used to encode the size and the subject hash is calculated
from the subject.

The Bridge, Message Digest and Subject are encoded in Type Length Value format.
The Bridge is a 128 bit identity of the sender.  The Message Digest is the
authentication field.  The receiving peer will authenticate that the message is
valid by using the Bridge to look up the 512 bit session key of the sender and
calculate an HMAC using the message data with the session key and compare it
to the value contained in the Message Digest.  In addition, there are sequence
numbers and time stamps present that prevent the replay of each message frame.

The 4 multicast path options will select the one of the equal cost paths
calculated from the current link state.  Every peer can calculate these paths
using the same replicated link state database, this results in 4 forwarding
trees to the same destinations if there are enough redundant links.

System Subjects
~~~~~~~~~~~~~~~

The peers exchange messages to authenticate new peers, synchronize the link
state of the network, subscription updates, and heartbeats to maintain neighbor
links.  These types of messages have unique subject prefixes as well as bits in
the message type header indicating whether it is special.

There are 7 classes subject prefixes used:

[%autowidth,options="header",grid="cols",stripes="even"]
|==========================================
| Prefix  | Description
| _I.     | Inbox point to point
| _M.     | Generic multicast message
| _X.     | Heartbeat link presence message
| _Z.     | Link state broadcast message
| _S.     | Normal subscription broadcast message
| _P.     | Pattern subscription broadcast message
| _N.     | Peer statistics multicast message
|==========================================

A broadcast style forwarding used by _Z, _S, _P subjects is different from
multicast forwarding.  It will flood the authenticated peers in the network,
adjusting each peer's routing database as it is received.  It uses this type of
forwarding because this kind of update may cause the multicast forwarding to be
temporarily incomplete until the network converges again.

The forwarding path for the Inbox, Heartbeat and broadcast subjects does not
follow the multicast forwarding path, so they can't be subscribed.

There is a separate sequence number domain defined for these because of the
idempotent nature of maintaining the replicated state of the network.  If a
peer misses messages for a delta changes in the subscriptions or links
database, the state is reinitialized by replicating it from an up to date peer.

The multicast subjects follow normal forwarding rules.  The _M prefix is used
for a multicast ping.

The _N prefix has unique subjects for link and peer statistics like messages
sent or received, bytes sent or received, as well as adjacency notifications.
These are used to monitor an individual node or a group of them with pattern
subscriptions.  These stats are not sent unless there are subscriptions open.

Heartbeat Subjects
~~~~~~~~~~~~~~~~~~

These are sent on a link between directly connected peers.

[%autowidth,options="header",grid="cols",stripes="even"]
|==========================================
| Subject  | Description
| _X.HELLO | First message sent
| _X.HB    | Periodic message
| _X.BYE   | Last message sent
| _X.NAME  | Link discovery message
|==========================================

- _X.HELLO and _X.HB messages have two functions, the first is to initiate the
  authentication key exchange.  The second is to keep a peer up to date with
  the last sequence numbers used by the subscription and link state.  When
  heartbeats are not received within 1.5 intervals.  The interval default is 10
  seconds, this causes a link to be deactivated at :15 when HB expected at :10.
  When all of the direct links to a peer are inactive, then the peer is
  unauthenticated and marked as a zombie.  The heartbeat timeout does not
  depend on a transport timeout, like a TCP reset.  The result of this behavior
  is that overloaded or congested links that delay messages for longer than the
  1.5 times the heartbeat interval will may incur message loss.  This puts an
  upper bound on the link latency and alleviates back pressure to the publisher.

- _X.BYE causes the peer to be unauthenticated and dropped from the peer db.

- _X.NAME messages are multicast to a device for presence detection.  Links
  between peers are only established when the type and name of a transport is
  matched within a service.

Link State Subjects
~~~~~~~~~~~~~~~~~~~

These are broadcast flooded to authenticated peers.

[%autowidth,options="header",grid="cols",stripes="even"]
|==========================================
| Subject  | Description
| _Z.ADD   | New peer added to peer db
| _Z.DEL   | Dropped peer from peer db
| _Z.BLM   | Subscription bloom filter resized
| _Z.ADJ   | Adjacency changed, link added or removed
|==========================================

- _Z.ADD is broadcast when a new peer is added to the peer db, usually as a
  result of authentication and also in the case that then network split and
  peers were joined again.

- _Z.DEL is broadcast when a peer sent a _X.BYE or if it is no longer reachable
  because all routes to it are down.

- _Z.BLM is broadcast when a peer resizes the bloom filter associated with the
  subscriptions and patterns it has open, this occurs approximately when
  crossing powers of two subscription counts (currently at 31, 62, 124, 248,
  ...).

- _Z.ADJ notifies when a peer adds are subtracts a link to another peer.  It
  increments the link state sequence number so that peers apply this update
  only when the link state reflects the current state, otherwise a RPC
  synchronization request is used (_I.[bridge].sync_req) to resync.

Subscription Subjects
~~~~~~~~~~~~~~~~~~~~~

These are broadcast flooded to authenticated peers.  They are updates to the
bloom filter that can be missed and resynchronized with _Z.BLM or a resync
RPC request.

[%autowidth,options="header",grid="cols",stripes="even"]
|==========================================
| Subject  | Description
| _S.JOIN  | Start a subscription
| _S.LEAV  | Stop a subscription
| _P.PSUB  | Start a pattern subscription
| _P.STOP  | Stop a pattern subscription
|==========================================

- _S.JOIN and _S.LEAV add and subtract subscriptions to a subject.

- _P.PSUB and _P.STOP add and subtract pattern subscriptions.  These contain
a pattern type as well as the pattern string.

Inbox Subjects
~~~~~~~~~~~~~~

The format of a subject with an _I. prefix also encodes the destination of the
message by appending the 128 bridge id in base64.

Example:

----
_I.duBVZZwXfwBVlYgGNUZQTw.auth
----

All of the peers along the path to the destination use this bridge id to
forward the message using the rules for the point to point route of the
destination peer.  This may be a TCP link or it may be a UDP Inbox link in the
case of a multicast PGM transport.  The suffix if the inbox subject indicate
the type of request or reply it is.  If the suffix is an integer then the
endpoint is not a system function, but information requested by the console
session or a web interface that is usually converted to text and displayed.

These suffixes are currently recognized:

[%autowidth,options="header",grid="cols",stripes="even"]
|==========================================
| Suffix    | Description
| auth      | Request authentication, peer verifies with user or service pub key
| subs      | Request and match active subscriptions strings with a pattern
| ping      | Request a pong reply, also has seqnos for maintaining state
| pong      | A reply to a ping, has latency information and update clock skew
| rem       | Remote admin request, run a console command from another peer
| add_rte   | After authenticated with peer, it will add other peers it knows
| sync_req  | Peer sends when it finds an old peer db or subscription state
| sync_rpy  | Response to a sync_req, includes current state if it is out of date
| bloom_req | Peer requests bloom state, currently peers use adj_req instead
| bloom_rpy | Response to a bloom_req, contains the bloom map of the subscriptions
| adj_req   | Peer requests when it finds an old link state or subscription state
| adj_rpy   | Response to adj_rpy, contains an up to date link state and bloom map for peer
| mesh_req  | Peer requests when it detects a missing mesh member
| mesh_rpy  | Response to mesh_rpy, contains missing link URLs
| trace     | Response to messages which have the Trace option flag in header
| ack       | Response to messages which have the Ack option flag in header
| any       | Encapsulates a peer _INBOX message, for point to point routing
|==========================================

- Auth does a key exchange between two peers.  After completing successfully,
  each peer has a session key for the other.  This allows messages to be
  sent by the other to be authenticated using Message Digest field.

- Subs is a request for the open subscriptions.  It is used by the console and
  the web interface for examining the network.  The RPC reply is always a
  numeric string to forward to the terminal or web page that requested it.

- Ping and pong are latency gathering functions for any two peers in the
  network, not necessarily directly connected.  The current sequence numbers
  for the link state and subscription state are also exchanged for synchronizing
  peers which are not directly connected.

- Rem is a remote console command execution, used in the console and web
  interfaces.

- Add_rte is used after the auth key exchange to replicate the peer db to a new
  peer.  This initial peer db only contains the names and bridge ids, so the
  new peer must request session keys, link state and subscription state for
  peers it does not already know about.

- Sync_req and sync_rpy are used replicate the session keys.  If a new peer
  does not have the session info from a _Z.ADD or a add_rte, it will request it
  from the peer that notified of the unknown peer session.  This will often be
  the case after authentication occurs and the new peer receives an add_rte
  from an older peer that has a db with the current state of the network.  This
  is the only other way that the unique session keys for each peer is
  distributed besides directly authenticating with a key exchange.  The sync_rpy
  also includes the link state and subscription bloom filter of requested peer.

- Bloom_req and bloom_rpy are RPCs for the subscription bloom filter.  The
  adj_req and adj_rpy are used instead for this info.

- Adj_req and adj_rpy are the main method that peers recover the current link
  state and subscription state.  They work in a RPC request/response style.
  The request contains the sequence numbers that the source peer has in it's
  db.  The destination peer compares these numbers with it's own db and replies
  when a sequence needs updating.  Usually the destination peer is the one that
  the source needs synchronized, but a closer peer can be queried as well.
  This occurs when a lot of peers need to resynchronize as a result of a
  network split and reconnect.

- Mesh_req and mesh_rpy are RPCs for distributing URLs for peers in the same
  mesh network.  When a peer connects to a mesh, it uses the initial connection
  to find the addresses of all the other peers in the mesh with this RPC.
 
- Trace and ack are sent as a multicast message is forwarded with the Message
  Options set in the header.  These can be requested from a console publish
  using the "trace" or "ack" commands.

- Any encapsulates an _INBOX point to point message and forwards it to the
  correct peer.  An _INBOX publish does not have a destination other than a
  unique subject that another peer has subscribed, for example
  "_INBOX.7F000001.2202C25FE975070A48320.>".  The peer that encapsulates this
  message finds the possible destinations by testing the bloom filters it has
  and then forwards to the matching peers.  The usual case is that there is
  only one matching destination.

[[example_message_flow]]
Example Message Flow
~~~~~~~~~~~~~~~~~~~~

Two peers key exchange, ruby connecting to dyna:

[%autowidth,options="header",grid="cols",stripes="even"]
|==========================================
| Packet | Subject   | Source | Destination | Description
| ruby.1 | _X.HELLO  | ruby   | dyna        | initial hello message after connection
| dyna.1 | _I.xq6vl+2HcoDxtt+7lC7dGQ.auth | dyna | ruby | dyna authenticates with ruby
| ruby.2 | _I.wwEnbQEY2FMuwZGSjpi3jQ.auth | ruby | dyna | ruby authenticates with dyna
| ruby.2 | _Z.ADD    | ruby   | dyna        | ruby adds dyna to peer db
| ruby.2 | _Z.ADJ    | ruby   | dyna        | ruby adds link to dyna
| dyna.2 | _Z.ADJ    | dyna   | ruby        | dyna adds link to ruby
| dyna.2 | _I.xq6vl+2HcoDxtt+7lC7dGQ.auth | dyna | ruby | dyna confirms authentication
| dyna.2 | _Z.ADD    | dyna   | ruby        | dyna adds ruby to peer db
|==========================================

Ruby connecting dyna, a member of a network of 4 nodes: dyna, zero, one, and
two.  This is the message flow between ruby and dyna, which completes the initial
synchronization of ruby.

[%autowidth,options="header",grid="cols",stripes="even"]
|==========================================
| Packet | Subject   | Source | Destination | Description
| ruby.1 | _X.HELLO  | ruby   | dyna        | initial hello message after connection
| dyna.1 | _I.q6pEpnzNyANEZKKp29532Q.auth | dyna | ruby | dyna authenticates with ruby
| ruby.2 | _I.tXB702RHKF0M69dl7K7vrw.auth | ruby | dyna | ruby authenticates with dyna
| ruby.2 | _Z.ADD    | ruby   | dyna        | ruby adds dyna to peer db
| ruby.2 | _Z.ADJ    | ruby   | dyna        | ruby adds link to dyna
| ruby.2 | _I.tXB702RHKF0M69dl7K7vrw.adj_req | ruby | dyna | ruby requests adjacency of dyna
| dyna.2 | _Z.ADJ    | dyna   | ruby      | dyna adds link to ruby
| dyna.2 | _I.q6pEpnzNyANEZKKp29532Q.auth | dyna | ruby | dyna confirms authentication
| dyna.2 | _Z.ADD    | dyna   | ruby      | dyna adds ruby to peer db
| dyna.2 | _I.q6pEpnzNyANEZKKp29532Q.add_rte | dyna | ruby | dyna populates ruby peer db of other peers
| dyna.2 | _I.q6pEpnzNyANEZKKp29532Q.adj_rpy | dyna | ruby | dyna replies to adj_req, links to other peers
| ruby.3 | _I.tXB702RHKF0M69dl7K7vrw.sync_req | ruby | dyna | ruby requests sync of peer zero from dyna
| ruby.3 | _I.tXB702RHKF0M69dl7K7vrw.sync_req | ruby | dyna | ruby requests sync of peer one from dyna
| ruby.3 | _I.tXB702RHKF0M69dl7K7vrw.sync_req | ruby | dyna | ruby requests sync of peer two from dyna
| dyna.3 | _I.q6pEpnzNyANEZKKp29532Q.sync_rpy | dyna | ruby | dyna replies key, links, bloom for peer zero
| dyna.3 | _I.q6pEpnzNyANEZKKp29532Q.sync_rpy | dyna | ruby | dyna replies key, links, bloom for peer one
| dyna.3 | _I.q6pEpnzNyANEZKKp29532Q.sync_rpy | dyna | ruby | dyna replies key, links, bloom for peer two
|==========================================

There is also message flow between dyna and zero, one, two.  This is the flow between dyna and zero.  The
message flow between dyna and one, dyna and two is the same as dyna and zero.

[%autowidth,options="header",grid="cols",stripes="even"]
|==========================================
| Packet | Subject   | Source | Destination | Description
| dyna.1 | _Z.ADJ    | dyna   | zero        | dyna notifies the new link from dyna to ruby
| dyna.1 | _Z.ADD    | dyna   | zero        | dyna notifies the add ruby to peer db
| dyna.1 | _Z.ADJ    | ruby   | zero        | forward from ruby for new link from ruby to dyna
| zero.1 | _I.tXB702RHKF0M69dl7K7vrw.sync_req | zero | dyna | zero requests sync of peer ruby from dyna
| dyna.2 | _I.ia988C6TtC6/L3JC6D3GqA.sync_rpy | dyna | zero | dyna replies key, links, bloom for peer ruby
| zero.2 | _Z.ADD    | zero   | dyna        | zero notifies the add of ruby to peer db
|==========================================

Adding ruby to the network ripples through the directly connected peers, which
discover the new peer from the broadcasting of the _Z.ADD messages and then
synchronize with each other to merge the ruby session key, the link state, and
the subscription bloom state into the network state.
